apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerprimary
spec:
  selector:
    matchLabels:
      app: containerprimary
  template:
    metadata:
      labels:
        app: containerprimary
    spec:       
      containers:
      - name: containerprimary
        image: comunidadcontainerregistry.azurecr.io/containerprimary:v1
        ports:
          - containerPort: 80